// Do not edit this file; automatically generated by build.py.
'use strict';

var SparqlBlocks={Blocks:{}};/*


 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
SparqlBlocks.Blocks.bgp={};var typeExt=SparqlBlocks.Types.getExtension,_init=function(a){a.setHelpUrl("http://www.w3.org/TR/sparql11-query/#QSynTriples")},_initVerb=function(a){_init(a);a.setColour(65)},_initSubject=function(a){_init(a);a.setColour(120)},_varsInScopeFromInput=function(a,b){if(a.getInputConnection(b)){var c=b.targetBlock;if(c&&(c=c.varsInScope()))return c}return[]};
Blockly.Blocks.sparql_verb_objectlist={init:function(){_initVerb(this);this.appendValueInput("VERB").setCheck(typeExt("Verb"));this.appendStatementInput("OBJECT").setCheck("ObjectList").appendField("\u21b3");this.setInputsInline(!0);this.setPreviousStatement(!0,"PropertyList");this.setNextStatement(!0,"PropertyList");this.setTooltip("")},getVarsInScope:function(){return _.union(_varsInScopeFromInput(this,"VERB"),_varsInScopeFromInput(this,"OBJECT"))}};
Blockly.Blocks.sparql_verb_object={init:function(){_initVerb(this);this.appendValueInput("VERB").setCheck(typeExt("Verb"));this.appendValueInput("OBJECT").setCheck(typeExt("GraphTermOrVar")).appendField("is");this.setInputsInline(!0);this.setPreviousStatement(!0,"PropertyList");this.setNextStatement(!0,"PropertyList");this.setTooltip("")}};
Blockly.Blocks.sparql_reverseVerb_object={init:function(){_initVerb(this);this.appendValueInput("VERB").setCheck(typeExt("Verb")).appendField("is");this.appendValueInput("OBJECT").setCheck(typeExt("GraphTermOrVar")).appendField("of");this.setInputsInline(!0);this.setPreviousStatement(!0,"PropertyList");this.setNextStatement(!0,"PropertyList");this.setTooltip("")}};
Blockly.Blocks.sparql_isa={init:function(){_initVerb(this);this.appendValueInput("TYPE").setCheck(typeExt("ResourceOrVar")).appendField("is a");this.setInputsInline(!0);this.setPreviousStatement(!0,"PropertyList");this.setNextStatement(!0,"PropertyList");this.setTooltip("")}};
Blockly.Blocks.sparql_subject_propertylist={init:function(){_initSubject(this);this.appendValueInput("SUBJECT").setCheck(typeExt("ResourceOrVar"));this.appendStatementInput("PROPERTY_LIST").setCheck("PropertyList").appendField("  \u230a");this.setInputsInline(!0);this.setPreviousStatement(!0,"TriplesBlock");this.setNextStatement(!0,"TriplesBlock");this.setTooltip("")}};
Blockly.Blocks.sparql_typedsubject_propertylist={init:function(){_initSubject(this);this.appendValueInput("SUBJECT").setCheck(typeExt("ResourceOrVar"));this.appendValueInput("TYPE").setCheck(typeExt("ResourceOrVar")).appendField("is a");this.appendStatementInput("PROPERTY_LIST").setCheck("PropertyList").appendField("  &");this.setInputsInline(!0);this.setPreviousStatement(!0,"TriplesBlock");this.setNextStatement(!0,"TriplesBlock");this.setTooltip("")}};
Blockly.Blocks.sparql_anonsubject_propertylist={init:function(){_initSubject(this);this.appendStatementInput("PROPERTY_LIST").setCheck("PropertyList").appendField("s.t.");this.setInputsInline(!0);this.setOutput(!0,"Resource");this.setTooltip("")}};
Blockly.Blocks.sparql_subject_verb_objectlist={init:function(){_initSubject(this);this.appendValueInput("SUBJECT").setCheck(typeExt("ResourceOrVar"));this.appendValueInput("VERB").appendField("has").setCheck(typeExt("Verb"));this.appendStatementInput("OBJECT_LIST").setCheck("ObjectList").appendField("\u21b3");this.setInputsInline(!0);this.setPreviousStatement(!0,"TriplesBlock");this.setNextStatement(!0,"TriplesBlock");this.setTooltip("")}};
Blockly.Blocks.sparql_subject_verb_object={init:function(){_initSubject(this);this.appendValueInput("SUBJECT").setCheck(typeExt("ResourceOrVar"));this.appendValueInput("VERB").appendField("has").setCheck(typeExt("Verb"));this.appendValueInput("OBJECT").setCheck(typeExt("GraphTermOrVar")).appendField("\u2192");this.setInputsInline(!0);this.setPreviousStatement(!0,"TriplesBlock");this.setNextStatement(!0,"TriplesBlock");this.setTooltip("")}};/*


 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
SparqlBlocks.Blocks.control={};typeExt=SparqlBlocks.Types.getExtension;Blockly.Blocks.sparql_filter={init:function(){this.setHelpUrl("http://www.example.com/");this.setColour(210);this.appendValueInput("CONDITION").setCheck(typeExt("BooleanExpr")).appendField("provided that");this.setInputsInline(!0);this.setPreviousStatement(!0,"TriplesBlock");this.setNextStatement(!0,"TriplesBlock");this.setTooltip("")}};
Blockly.Blocks.sparql_union={init:function(){this.setHelpUrl("http://www.example.com/");this.setColour(260);this.appendStatementInput("OP1").setCheck("TriplesBlock");this.appendStatementInput("OP2").setCheck("TriplesBlock").appendField("or");this.setInputsInline(!0);this.setPreviousStatement(!0,"TriplesBlock");this.setNextStatement(!0,"TriplesBlock");this.setTooltip("")}};
Blockly.Blocks.sparql_optional={init:function(){this.setHelpUrl("http://www.example.com/");this.setColour(260);this.appendStatementInput("OP").setCheck("TriplesBlock").appendField("optionally");this.setInputsInline(!0);this.setPreviousStatement(!0,"TriplesBlock");this.setNextStatement(!0,"TriplesBlock");this.setTooltip("")}};/*


 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
SparqlBlocks.Blocks.exec={};var typeExt=SparqlBlocks.Types.getExtension,unconnect_=function(a){(a=a.targetBlock())&&a.dispose()};Blockly.Blocks.sparql_execution={init:function(){this.setHelpUrl("http://www.example.com/");this.setColour(330);this.appendValueInput("QUERY").setCheck("Select").appendField(" \u2699");this.appendValueInput("RESULTS").setCheck("Table").appendField("\u21aa");this.setTooltip("")},onchange:function(){SparqlBlocks.Exec.blockExec(this)}};
Blockly.Blocks.sparql_execution_in_progress={init:function(){this.setHelpUrl("http://www.example.com/");this.setColour(330);this.appendDummyInput().appendField("execution in progress...");this.setOutput(!0,"Table");this.setTooltip("");this.setDeletable(!1);this.setMovable(!1);this.setEditable(!1)}};
Blockly.Blocks.sparql_execution_error={init:function(){this.setHelpUrl("http://www.example.com/");this.setColour(330);this.appendDummyInput().appendField("Error executing query!");this.appendDummyInput().appendField("Error Name").appendField(new Blockly.FieldTextInput("ERROR TYPE"),"ERRORTYPE");this.appendDummyInput().appendField("Description").appendField(new Blockly.FieldTextInput("ERROR"),"ERRORDESCR");this.setOutput(!0,"Table");this.setTooltip("");this.setDeletable(!1);this.setMovable(!1);this.setEditable(!1)}};/*

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
SparqlBlocks.Blocks.logic={};typeExt=SparqlBlocks.Types.getExtension;SparqlBlocks.Blocks.logic.HUE=210;
Blockly.Blocks.sparql_logic_compare={init:function(){var a=this.RTL?[["=","EQ"],["\u2260","NEQ"],[">","LT"],["\u2265","LTE"],["<","GT"],["\u2264","GTE"]]:[["=","EQ"],["\u2260","NEQ"],["<","LT"],["\u2264","LTE"],[">","GT"],["\u2265","GTE"]];this.setHelpUrl(Blockly.Msg.LOGIC_COMPARE_HELPURL);this.setColour(SparqlBlocks.Blocks.logic.HUE);this.setOutput(!0,"BooleanExpr");this.appendValueInput("A");this.appendValueInput("B").appendField(new Blockly.FieldDropdown(a),"OP");this.setInputsInline(!0);var b=
this;this.setTooltip(function(){var a=b.getFieldValue("OP");return{EQ:Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ,NEQ:Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ,LT:Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT,LTE:Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE,GT:Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT,GTE:Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE}[a]});this.prevBlocks_=[null,null]},onchange:function(){if(this.workspace){var a=this.getInputTargetBlock("A"),b=this.getInputTargetBlock("B");if(a&&b&&!a.outputConnection.checkType_(b.outputConnection))for(var c=
0;c<this.prevBlocks_.length;c++){var e=this.prevBlocks_[c];if(e===a||e===b)e.setParent(null),e.bumpNeighbours_()}this.prevBlocks_[0]=a;this.prevBlocks_[1]=b}}};
Blockly.Blocks.sparql_logic_operation={init:function(){var a=[[Blockly.Msg.LOGIC_OPERATION_AND,"AND"],[Blockly.Msg.LOGIC_OPERATION_OR,"OR"]];this.setHelpUrl(Blockly.Msg.LOGIC_OPERATION_HELPURL);this.setColour(SparqlBlocks.Blocks.logic.HUE);this.setOutput(!0,"BooleanExpr");this.appendValueInput("A").setCheck(typeExt("BooleanExpr"));this.appendValueInput("B").setCheck(typeExt("BooleanExpr")).appendField(new Blockly.FieldDropdown(a),"OP");this.setInputsInline(!0);var b=this;this.setTooltip(function(){var a=
b.getFieldValue("OP");return{AND:Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND,OR:Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR}[a]})}};Blockly.Blocks.sparql_logic_negate={init:function(){this.jsonInit({message0:Blockly.Msg.LOGIC_NEGATE_TITLE,args0:[{type:"input_value",name:"BOOL",check:typeExt("BooleanExpr")}],output:"BooleanExpr",colour:SparqlBlocks.Blocks.logic.HUE,tooltip:Blockly.Msg.LOGIC_NEGATE_TOOLTIP,helpUrl:Blockly.Msg.LOGIC_NEGATE_HELPURL})}};
Blockly.Blocks.sparql_logic_boolean={init:function(){var a=[[Blockly.Msg.LOGIC_BOOLEAN_TRUE,"TRUE"],[Blockly.Msg.LOGIC_BOOLEAN_FALSE,"FALSE"]];this.setHelpUrl(Blockly.Msg.LOGIC_BOOLEAN_HELPURL);this.setColour(SparqlBlocks.Blocks.logic.HUE);this.setOutput(!0,"LiteralBoolean");this.appendDummyInput().appendField(new Blockly.FieldDropdown(a),"BOOL");this.setTooltip(Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP)}};
Blockly.Blocks.sparql_logic_null={init:function(){this.setHelpUrl(Blockly.Msg.LOGIC_NULL_HELPURL);this.setColour(SparqlBlocks.Blocks.logic.HUE);this.setOutput(!0);this.appendDummyInput().appendField(Blockly.Msg.LOGIC_NULL);this.setTooltip(Blockly.Msg.LOGIC_NULL_TOOLTIP)}};
Blockly.Blocks.sparql_logic_ternary={init:function(){this.setHelpUrl(Blockly.Msg.LOGIC_TERNARY_HELPURL);this.setColour(SparqlBlocks.Blocks.logic.HUE);this.appendValueInput("IF").setCheck(typeExt("BooleanExpr")).appendField(Blockly.Msg.LOGIC_TERNARY_CONDITION);this.appendValueInput("THEN").appendField(Blockly.Msg.LOGIC_TERNARY_IF_TRUE);this.appendValueInput("ELSE").appendField(Blockly.Msg.LOGIC_TERNARY_IF_FALSE);this.setOutput(!0,"Expr");this.setTooltip(Blockly.Msg.LOGIC_TERNARY_TOOLTIP);this.prevParentConnection_=
null},onchange:function(){if(this.workspace){var a=this.getInputTargetBlock("THEN"),b=this.getInputTargetBlock("ELSE"),c=this.outputConnection.targetConnection;if((a||b)&&c)for(var e=0;2>e;e++){var d=1==e?a:b;d&&!d.outputConnection.checkType_(c)&&(c===this.prevParentConnection_?(this.setParent(null),c.sourceBlock_.bumpNeighbours_()):(d.setParent(null),d.bumpNeighbours_()))}this.prevParentConnection_=c}}};
Blockly.Blocks.sparql_exists={init:function(){this.setHelpUrl("");this.setColour(SparqlBlocks.Blocks.logic.HUE);this.setOutput(!0,"BooleanExpr");this.appendStatementInput("OP").setCheck("TriplesBlock").appendField("exists");this.setTooltip("")}};Blockly.Blocks.sparql_not_exists={init:function(){this.setHelpUrl("");this.setColour(SparqlBlocks.Blocks.logic.HUE);this.setOutput(!0,"BooleanExpr");this.appendStatementInput("OP").setCheck("TriplesBlock").appendField("not exists");this.setTooltip("")}};/*


 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
SparqlBlocks.Blocks.main={};typeExt=SparqlBlocks.Types.getExtension;Blockly.Blocks.sparql_construct={init:function(){this.setHelpUrl("http://www.example.com/");this.setColour(290);this.appendDummyInput().appendField("CONSTRUCT");this.appendStatementInput("CONSTRUCT").setCheck("ConstructTriples");this.appendDummyInput().appendField("WHERE");this.appendStatementInput("WHERE").setCheck("TriplesBlock");this.setTooltip("")}};
Blockly.Blocks.sparql_select={init:function(){this.setHelpUrl("http://www.example.com/");this.setColour(290);this.appendDummyInput().appendField("select all the variables");this.appendStatementInput("WHERE").setCheck("TriplesBlock").appendField("where");this.appendValueInput("ORDER_FIELD1").setCheck(typeExt("Expr")).appendField("ordered by").appendField(new Blockly.FieldDropdown([["\u2193","ASC"],["\u2191","DESC"]]),"ORDER_DIRECTION1");this.appendValueInput("ORDER_FIELD2").setCheck(typeExt("Expr")).appendField(", by").appendField(new Blockly.FieldDropdown([["\u2193",
"ASC"],["\u2191","DESC"]]),"ORDER_DIRECTION2");this.appendValueInput("ORDER_FIELD3").setCheck(typeExt("Expr")).appendField(", and by").appendField(new Blockly.FieldDropdown([["\u2193","ASC"],["\u2191","DESC"]]),"ORDER_DIRECTION3");this.appendDummyInput().appendField("limited to the first").appendField(new Blockly.FieldTextInput("10"),"LIMIT").appendField("rows");this.setOutput(!0,"Select");this.setInputsInline(!0);this.setTooltip("")}};
Blockly.Blocks.sparql_var_binding={init:function(){this.setHelpUrl("http://www.example.com/");this.setColour(330);this.appendValueInput("EXPR").setCheck(typeExt("Expr"));this.appendDummyInput().appendField("as").appendField(new Blockly.FieldTextInput("col name"),"COLNAME");this.setInputsInline(!0);this.setPreviousStatement(!0,"VarBindings");this.setNextStatement(!0,"VarBindings");this.setTooltip("")}};
Blockly.Blocks.sparql_prefixed_iri={init:function(){this.setHelpUrl("http://www.example.com/");this.setColour(20);this.appendDummyInput().appendField(new Blockly.FieldTextInput("prefix"),"PREFIX").appendField(":").appendField(new Blockly.FieldTextInput("localName"),"LOCAL_NAME");this.setInputsInline(!0);this.setOutput(!0,"Iri");this.setTooltip("")}};
Blockly.Blocks.sparql_iri={init:function(){this.setHelpUrl("http://www.example.com/");this.setColour(20);this.appendDummyInput().appendField("<").appendField(new Blockly.FieldTextInput("iri"),"IRI").appendField(">");this.setInputsInline(!0);this.setOutput(!0,"Iri");this.setTooltip("")}};/*

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
SparqlBlocks.Blocks.math={};typeExt=SparqlBlocks.Types.getExtension;SparqlBlocks.Blocks.math.HUE=230;Blockly.Blocks.sparql_math_number={init:function(){this.setHelpUrl(Blockly.Msg.MATH_NUMBER_HELPURL);this.setColour(SparqlBlocks.Blocks.math.HUE);this.appendDummyInput().appendField(new Blockly.FieldTextInput("0",Blockly.FieldTextInput.numberValidator),"NUM");this.setOutput(!0,"LiteralNumber");this.setTooltip(Blockly.Msg.MATH_NUMBER_TOOLTIP)}};
Blockly.Blocks.sparql_math_arithmetic={init:function(){var a=[[Blockly.Msg.MATH_ADDITION_SYMBOL,"ADD"],[Blockly.Msg.MATH_SUBTRACTION_SYMBOL,"MINUS"],[Blockly.Msg.MATH_MULTIPLICATION_SYMBOL,"MULTIPLY"],[Blockly.Msg.MATH_DIVISION_SYMBOL,"DIVIDE"]];this.setHelpUrl(Blockly.Msg.MATH_ARITHMETIC_HELPURL);this.setColour(SparqlBlocks.Blocks.math.HUE);this.setOutput(!0,"NumberExpr");this.appendValueInput("A").setCheck(typeExt("NumberExpr"));this.appendValueInput("B").setCheck(typeExt("NumberExpr")).appendField(new Blockly.FieldDropdown(a),
"OP");this.setInputsInline(!0);var b=this;this.setTooltip(function(){var a=b.getFieldValue("OP");return{ADD:Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD,MINUS:Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS,MULTIPLY:Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY,DIVIDE:Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE}[a]})}};
Blockly.Blocks.sparql_math_single={init:function(){var a=[[Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE,"ABS"],["-","NEG"]];this.setHelpUrl(Blockly.Msg.MATH_SINGLE_HELPURL);this.setColour(SparqlBlocks.Blocks.math.HUE);this.setOutput(!0,"NumberExpr");this.appendValueInput("NUM").setCheck(typeExt("NumberExpr")).appendField(new Blockly.FieldDropdown(a),"OP");var b=this;this.setTooltip(function(){var a=b.getFieldValue("OP");return{ABS:Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS,NEG:Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG}[a]})}};
Blockly.Blocks.sparql_math_number_property={init:function(){var a=[[Blockly.Msg.MATH_IS_EVEN,"EVEN"],[Blockly.Msg.MATH_IS_ODD,"ODD"],[Blockly.Msg.MATH_IS_PRIME,"PRIME"],[Blockly.Msg.MATH_IS_WHOLE,"WHOLE"],[Blockly.Msg.MATH_IS_POSITIVE,"POSITIVE"],[Blockly.Msg.MATH_IS_NEGATIVE,"NEGATIVE"],[Blockly.Msg.MATH_IS_DIVISIBLE_BY,"DIVISIBLE_BY"]];this.setColour(SparqlBlocks.Blocks.math.HUE);this.appendValueInput("NUMBER_TO_CHECK").setCheck(typeExt("NumberExpr"));a=new Blockly.FieldDropdown(a,function(a){this.sourceBlock_.updateShape_("DIVISIBLE_BY"==
a)});this.appendDummyInput().appendField(a,"PROPERTY");this.setInputsInline(!0);this.setOutput(!0,"BooleanExpr");this.setTooltip(Blockly.Msg.MATH_IS_TOOLTIP)},mutationToDom:function(){var a=document.createElement("mutation"),b="DIVISIBLE_BY"==this.getFieldValue("PROPERTY");a.setAttribute("divisor_input",b);return a},domToMutation:function(a){a="true"==a.getAttribute("divisor_input");this.updateShape_(a)},updateShape_:function(a){var b=this.getInput("DIVISOR");a?b||this.appendValueInput("DIVISOR").setCheck(typeExt("NumberExpr")):
b&&this.removeInput("DIVISOR")}};Blockly.Blocks.sparql_math_round={init:function(){var a=[[Blockly.Msg.MATH_ROUND_OPERATOR_ROUND,"ROUND"],[Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP,"ROUNDUP"],[Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN,"ROUNDDOWN"]];this.setHelpUrl(Blockly.Msg.MATH_ROUND_HELPURL);this.setColour(SparqlBlocks.Blocks.math.HUE);this.setOutput(!0,"NumberExpr");this.appendValueInput("NUM").setCheck(typeExt("NumberExpr")).appendField(new Blockly.FieldDropdown(a),"OP");this.setTooltip(Blockly.Msg.MATH_ROUND_TOOLTIP)}};
Blockly.Blocks.sparql_math_modulo={init:function(){this.jsonInit({message0:Blockly.Msg.MATH_MODULO_TITLE,args0:[{type:"input_value",name:"DIVIDEND",check:typeExt("NumberExpr")},{type:"input_value",name:"DIVISOR",check:typeExt("NumberExpr")}],inputsInline:!0,output:"NumberExpr",colour:SparqlBlocks.Blocks.math.HUE,tooltip:Blockly.Msg.MATH_MODULO_TOOLTIP,helpUrl:Blockly.Msg.MATH_MODULO_HELPURL})}};
Blockly.Blocks.sparql_math_constrain={init:function(){this.jsonInit({message0:Blockly.Msg.MATH_CONSTRAIN_TITLE,args0:[{type:"input_value",name:"VALUE",check:typeExt("NumberExpr")},{type:"input_value",name:"LOW",check:typeExt("NumberExpr")},{type:"input_value",name:"HIGH",check:typeExt("NumberExpr")}],inputsInline:!0,output:"NumberExpr",colour:SparqlBlocks.Blocks.math.HUE,tooltip:Blockly.Msg.MATH_CONSTRAIN_TOOLTIP,helpUrl:Blockly.Msg.MATH_CONSTRAIN_HELPURL})}};
Blockly.Blocks.sparql_math_random_int={init:function(){this.jsonInit({message0:Blockly.Msg.MATH_RANDOM_INT_TITLE,args0:[{type:"input_value",name:"FROM",check:typeExt("NumberExpr")},{type:"input_value",name:"TO",check:typeExt("NumberExpr")}],inputsInline:!0,output:"NumberExpr",colour:SparqlBlocks.Blocks.math.HUE,tooltip:Blockly.Msg.MATH_RANDOM_INT_TOOLTIP,helpUrl:Blockly.Msg.MATH_RANDOM_INT_HELPURL})}};
Blockly.Blocks.sparql_math_random_float={init:function(){this.setHelpUrl(Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL);this.setColour(SparqlBlocks.Blocks.math.HUE);this.setOutput(!0,"NumberExpr");this.appendDummyInput().appendField(Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM);this.setTooltip(Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP)}};/*


 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
SparqlBlocks.Blocks.tabular={};typeExt=SparqlBlocks.Types.getExtension;Blockly.Blocks.sparql_column={init:function(){this.setHelpUrl("http://www.example.com/");this.setColour(330);this.appendDummyInput().appendField(new Blockly.FieldTextInput("colName"),"COLNAME");this.appendStatementInput("VALUES").setCheck("ValueContainer");this.setOutput(!0,"Column");this.setDeletable(!1);this.setMovable(!1);this.setEditable(!1);this.setTooltip("")}};
Blockly.Blocks.sparql_value_container={init:function(){this.setHelpUrl("http://www.example.com/");this.setColour(330);this.appendValueInput("VALUE").setCheck(typeExt("GraphTerm"));this.setInputsInline(!0);this.setPreviousStatement(!0,"ValueContainer");this.setNextStatement(!0,"ValueContainer");this.setDeletable(!1);this.setMovable(!1);this.setTooltip("")}};
Blockly.Blocks.sparql_table={init:function(){this.setHelpUrl("http://www.example.com/");this.setColour(330);this.setInputsInline(!0);this.setOutput(!0,"Table");this.setDeletable(!1);this.setMovable(!1);this.setTooltip("");this.colCount_=0},mutationToDom:function(){if(!this.colCount_)return null;var a=document.createElement("mutation");this.colCount_&&a.setAttribute("colCount",this.colCount_);return a},domToMutation:function(a){this.colCount_=parseInt(a.getAttribute("colCount"),10);for(a=1;a<=this.colCount_;a++)this.appendValueInput("COL"+
a).setCheck("Column")},decompose:function(a){var b=Blockly.Block.obtain(a,"sparql_table_table");b.initSvg();for(var c=b.getInput("STACK").connection,e=1;e<=this.colCount_;e++){var d=Blockly.Block.obtain(a,"sparql_table_column");d.initSvg();c.connect(d.previousConnection);c=d.nextConnection}return b},compose:function(a){for(var b=this.colCount_;0<b;b--)this.removeInput("COL"+b);this.colCount_=0;for(a=a.getInputTargetBlock("STACK");a;){switch(a.type){case "sparql_table_column":this.colCount_++;b=this.appendValueInput("COL"+
this.colCount_).setCheck("Column");a.valueConnection_&&b.connection.connect(a.valueConnection_);break;default:throw"Unknown block type.";}a=a.nextConnection&&a.nextConnection.targetBlock()}},saveConnections:function(a){a=a.getInputTargetBlock("STACK");for(var b=1;a;){switch(a.type){case "sparql_table_column":var c=this.getInput("COL"+b);a.valueConnection_=c&&c.connection.targetConnection;b++;break;default:throw"Unknown block type.";}a=a.nextConnection&&a.nextConnection.targetBlock()}}};
Blockly.Blocks.sparql_table_table={init:function(){this.setColour(330);this.appendDummyInput().appendField("table");this.appendStatementInput("STACK");this.setTooltip("");this.contextMenu=!1}};Blockly.Blocks.sparql_table_column={init:function(){this.setColour(330);this.appendDummyInput().appendField("column");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("");this.contextMenu=!1}};/*

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
SparqlBlocks.Blocks.text={};typeExt=SparqlBlocks.Types.getExtension;SparqlBlocks.Blocks.text.HUE=160;
Blockly.Blocks.sparql_text={init:function(){this.setHelpUrl(Blockly.Msg.TEXT_TEXT_HELPURL);this.setColour(SparqlBlocks.Blocks.text.HUE);this.appendDummyInput().appendField(this.newQuote_(!0)).appendField(new Blockly.FieldTextInput(""),"TEXT").appendField(this.newQuote_(!1));this.setOutput(!0,"LiteralString");this.setTooltip(Blockly.Msg.TEXT_TEXT_TOOLTIP)},newQuote_:function(a){return new Blockly.FieldImage(a==this.RTL?"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAKCAQAAAAqJXdxAAAAqUlEQVQI1z3KvUpCcRiA8ef9E4JNHhI0aFEacm1o0BsI0Slx8wa8gLauoDnoBhq7DcfWhggONDmJJgqCPA7neJ7p934EOOKOnM8Q7PDElo/4x4lFb2DmuUjcUzS3URnGib9qaPNbuXvBO3sGPHJDRG6fGVdMSeWDP2q99FQdFrz26Gu5Tq7dFMzUvbXy8KXeAj57cOklgA+u1B5AoslLtGIHQMaCVnwDnADZIFIrXsoXrgAAAABJRU5ErkJggg==":
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAKCAQAAAAqJXdxAAAAn0lEQVQI1z3OMa5BURSF4f/cQhAKjUQhuQmFNwGJEUi0RKN5rU7FHKhpjEH3TEMtkdBSCY1EIv8r7nFX9e29V7EBAOvu7RPjwmWGH/VuF8CyN9/OAdvqIXYLvtRaNjx9mMTDyo+NjAN1HNcl9ZQ5oQMM3dgDUqDo1l8DzvwmtZN7mnD+PkmLa+4mhrxVA9fRowBWmVBhFy5gYEjKMfz9AylsaRRgGzvZAAAAAElFTkSuQmCC",12,12,'"')}};
Blockly.Blocks.sparql_text_with_lang={init:function(){this.setHelpUrl(Blockly.Msg.TEXT_TEXT_HELPURL);this.setColour(SparqlBlocks.Blocks.text.HUE);this.appendDummyInput().appendField(this.newQuote_(!0)).appendField(new Blockly.FieldTextInput(""),"TEXT").appendField(this.newQuote_(!1)).appendField("@").appendField(new Blockly.FieldTextInput(""),"LANG");this.setOutput(!0,"LiteralString");this.setTooltip(Blockly.Msg.TEXT_TEXT_TOOLTIP)},newQuote_:function(a){return new Blockly.FieldImage(a==this.RTL?"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAKCAQAAAAqJXdxAAAAqUlEQVQI1z3KvUpCcRiA8ef9E4JNHhI0aFEacm1o0BsI0Slx8wa8gLauoDnoBhq7DcfWhggONDmJJgqCPA7neJ7p934EOOKOnM8Q7PDElo/4x4lFb2DmuUjcUzS3URnGib9qaPNbuXvBO3sGPHJDRG6fGVdMSeWDP2q99FQdFrz26Gu5Tq7dFMzUvbXy8KXeAj57cOklgA+u1B5AoslLtGIHQMaCVnwDnADZIFIrXsoXrgAAAABJRU5ErkJggg==":
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAKCAQAAAAqJXdxAAAAn0lEQVQI1z3OMa5BURSF4f/cQhAKjUQhuQmFNwGJEUi0RKN5rU7FHKhpjEH3TEMtkdBSCY1EIv8r7nFX9e29V7EBAOvu7RPjwmWGH/VuF8CyN9/OAdvqIXYLvtRaNjx9mMTDyo+NjAN1HNcl9ZQ5oQMM3dgDUqDo1l8DzvwmtZN7mnD+PkmLa+4mhrxVA9fRowBWmVBhFy5gYEjKMfz9AylsaRRgGzvZAAAAAElFTkSuQmCC",12,12,'"')}};
Blockly.Blocks.sparql_text_with_type_pref={init:function(){this.setHelpUrl(Blockly.Msg.TEXT_TEXT_HELPURL);this.setColour(SparqlBlocks.Blocks.text.HUE);this.appendDummyInput().appendField(this.newQuote_(!0)).appendField(new Blockly.FieldTextInput(""),"TEXT").appendField(this.newQuote_(!1)).appendField("^^").appendField(new Blockly.FieldTextInput("prefix"),"DT_PREFIX").appendField(":").appendField(new Blockly.FieldTextInput("localName"),"DT_LOCAL_NAME");this.setOutput(!0,"LiteralString");this.setTooltip(Blockly.Msg.TEXT_TEXT_TOOLTIP)},
newQuote_:function(a){return new Blockly.FieldImage(a==this.RTL?"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAKCAQAAAAqJXdxAAAAqUlEQVQI1z3KvUpCcRiA8ef9E4JNHhI0aFEacm1o0BsI0Slx8wa8gLauoDnoBhq7DcfWhggONDmJJgqCPA7neJ7p934EOOKOnM8Q7PDElo/4x4lFb2DmuUjcUzS3URnGib9qaPNbuXvBO3sGPHJDRG6fGVdMSeWDP2q99FQdFrz26Gu5Tq7dFMzUvbXy8KXeAj57cOklgA+u1B5AoslLtGIHQMaCVnwDnADZIFIrXsoXrgAAAABJRU5ErkJggg==":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAKCAQAAAAqJXdxAAAAn0lEQVQI1z3OMa5BURSF4f/cQhAKjUQhuQmFNwGJEUi0RKN5rU7FHKhpjEH3TEMtkdBSCY1EIv8r7nFX9e29V7EBAOvu7RPjwmWGH/VuF8CyN9/OAdvqIXYLvtRaNjx9mMTDyo+NjAN1HNcl9ZQ5oQMM3dgDUqDo1l8DzvwmtZN7mnD+PkmLa+4mhrxVA9fRowBWmVBhFy5gYEjKMfz9AylsaRRgGzvZAAAAAElFTkSuQmCC",
12,12,'"')}};
Blockly.Blocks.sparql_text_with_type_iri={init:function(){this.setHelpUrl(Blockly.Msg.TEXT_TEXT_HELPURL);this.setColour(SparqlBlocks.Blocks.text.HUE);this.appendDummyInput().appendField(this.newQuote_(!0)).appendField(new Blockly.FieldTextInput(""),"TEXT").appendField(this.newQuote_(!1)).appendField("^^").appendField("<").appendField(new Blockly.FieldTextInput("iri"),"DT_IRI").appendField(">");this.setOutput(!0,"LiteralString");this.setTooltip(Blockly.Msg.TEXT_TEXT_TOOLTIP)},newQuote_:function(a){return new Blockly.FieldImage(a==this.RTL?
"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAKCAQAAAAqJXdxAAAAqUlEQVQI1z3KvUpCcRiA8ef9E4JNHhI0aFEacm1o0BsI0Slx8wa8gLauoDnoBhq7DcfWhggONDmJJgqCPA7neJ7p934EOOKOnM8Q7PDElo/4x4lFb2DmuUjcUzS3URnGib9qaPNbuXvBO3sGPHJDRG6fGVdMSeWDP2q99FQdFrz26Gu5Tq7dFMzUvbXy8KXeAj57cOklgA+u1B5AoslLtGIHQMaCVnwDnADZIFIrXsoXrgAAAABJRU5ErkJggg==":"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAKCAQAAAAqJXdxAAAAn0lEQVQI1z3OMa5BURSF4f/cQhAKjUQhuQmFNwGJEUi0RKN5rU7FHKhpjEH3TEMtkdBSCY1EIv8r7nFX9e29V7EBAOvu7RPjwmWGH/VuF8CyN9/OAdvqIXYLvtRaNjx9mMTDyo+NjAN1HNcl9ZQ5oQMM3dgDUqDo1l8DzvwmtZN7mnD+PkmLa+4mhrxVA9fRowBWmVBhFy5gYEjKMfz9AylsaRRgGzvZAAAAAElFTkSuQmCC",
12,12,'"')}};
Blockly.Blocks.sparql_text_join={init:function(){this.setHelpUrl(Blockly.Msg.TEXT_JOIN_HELPURL);this.setColour(SparqlBlocks.Blocks.text.HUE);this.itemCount_=2;this.updateShape_();this.setOutput(!0,"StringExpr");this.setMutator(new Blockly.Mutator(["text_create_join_item"]));this.setTooltip(Blockly.Msg.TEXT_JOIN_TOOLTIP)},mutationToDom:function(){var a=document.createElement("mutation");a.setAttribute("items",this.itemCount_);return a},domToMutation:function(a){this.itemCount_=parseInt(a.getAttribute("items"),10);
this.updateShape_()},decompose:function(a){var b=Blockly.Block.obtain(a,"text_create_join_container");b.initSvg();for(var c=b.getInput("STACK").connection,e=0;e<this.itemCount_;e++){var d=Blockly.Block.obtain(a,"text_create_join_item");d.initSvg();c.connect(d.previousConnection);c=d.nextConnection}return b},compose:function(a){a=a.getInputTargetBlock("STACK");for(var b=[],c=0;a;)b[c]=a.valueConnection_,a=a.nextConnection&&a.nextConnection.targetBlock(),c++;this.itemCount_=c;this.updateShape_();for(c=
0;c<this.itemCount_;c++)b[c]&&this.getInput("ADD"+c).connection.connect(b[c])},saveConnections:function(a){a=a.getInputTargetBlock("STACK");for(var b=0;a;){var c=this.getInput("ADD"+b);a.valueConnection_=c&&c.connection.targetConnection;b++;a=a.nextConnection&&a.nextConnection.targetBlock()}},updateShape_:function(){if(this.getInput("EMPTY"))this.removeInput("EMPTY");else for(var a=0;this.getInput("ADD"+a);)this.removeInput("ADD"+a),a++;if(0==this.itemCount_)this.appendDummyInput("EMPTY").appendField(this.newQuote_(!0)).appendField(this.newQuote_(!1));
else for(a=0;a<this.itemCount_;a++){var b=this.appendValueInput("ADD"+a);0==a&&b.appendField(Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH)}},newQuote_:Blockly.Blocks.sparql_text.newQuote_};Blockly.Blocks.sparql_text_create_join_container={init:function(){this.setColour(SparqlBlocks.Blocks.text.HUE);this.appendDummyInput().appendField(Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN);this.appendStatementInput("STACK");this.setTooltip(Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP);this.contextMenu=!1}};
Blockly.Blocks.sparql_text_create_join_item={init:function(){this.setColour(SparqlBlocks.Blocks.text.HUE);this.appendDummyInput().appendField(Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM);this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip(Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP);this.contextMenu=!1}};
Blockly.Blocks.sparql_text_append={init:function(){this.setHelpUrl(Blockly.Msg.TEXT_APPEND_HELPURL);this.setColour(SparqlBlocks.Blocks.text.HUE);this.appendValueInput("TEXT").appendField(Blockly.Msg.TEXT_APPEND_TO).appendField(new Blockly.FieldVariable(Blockly.Msg.TEXT_APPEND_VARIABLE),"VAR").appendField(Blockly.Msg.TEXT_APPEND_APPENDTEXT);this.setPreviousStatement(!0);this.setNextStatement(!0);var a=this;this.setTooltip(function(){return Blockly.Msg.TEXT_APPEND_TOOLTIP.replace("%1",a.getFieldValue("VAR"))})},
getVars:function(){return[this.getFieldValue("VAR")]},renameVar:function(a,b){Blockly.Names.equals(a,this.getFieldValue("VAR"))&&this.setFieldValue(b,"VAR")}};Blockly.Blocks.sparql_text_length={init:function(){this.jsonInit({message0:Blockly.Msg.TEXT_LENGTH_TITLE,args0:[{type:"input_value",name:"VALUE",check:typeExt("StringExpr")}],output:"NumberExpr",colour:SparqlBlocks.Blocks.text.HUE,tooltip:Blockly.Msg.TEXT_LENGTH_TOOLTIP,helpUrl:Blockly.Msg.TEXT_LENGTH_HELPURL})}};
Blockly.Blocks.sparql_text_isEmpty={init:function(){this.jsonInit({message0:Blockly.Msg.TEXT_ISEMPTY_TITLE,args0:[{type:"input_value",name:"VALUE",check:typeExt("StringExpr")}],output:"BooleanExpr",colour:SparqlBlocks.Blocks.text.HUE,tooltip:Blockly.Msg.TEXT_ISEMPTY_TOOLTIP,helpUrl:Blockly.Msg.TEXT_ISEMPTY_HELPURL})}};
Blockly.Blocks.sparql_text_indexOf={init:function(){var a=[[Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST,"FIRST"],[Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST,"LAST"]];this.setHelpUrl(Blockly.Msg.TEXT_INDEXOF_HELPURL);this.setColour(SparqlBlocks.Blocks.text.HUE);this.setOutput(!0,"NumberExpr");this.appendValueInput("VALUE").setCheck(typeExt("StringExpr")).appendField(Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT);this.appendValueInput("FIND").setCheck(typeExt("StringExpr")).appendField(new Blockly.FieldDropdown(a),
"END");Blockly.Msg.TEXT_INDEXOF_TAIL&&this.appendDummyInput().appendField(Blockly.Msg.TEXT_INDEXOF_TAIL);this.setInputsInline(!0);this.setTooltip(Blockly.Msg.TEXT_INDEXOF_TOOLTIP)}};
Blockly.Blocks.sparql_text_contains={init:function(){this.setHelpUrl(Blockly.Msg.TEXT_INDEXOF_HELPURL);this.setColour(SparqlBlocks.Blocks.text.HUE);this.setOutput(!0,"BooleanExpr");this.appendValueInput("FIND").setCheck(typeExt("StringExpr"));this.appendValueInput("VALUE").setCheck(typeExt("StringExpr")).appendField("is contained in");this.setInputsInline(!0);this.setTooltip("")}};
Blockly.Blocks.sparql_text_lang={init:function(){this.setHelpUrl(Blockly.Msg.TEXT_INDEXOF_HELPURL);this.setColour(SparqlBlocks.Blocks.text.HUE);this.setOutput(!0,"BooleanExpr");this.appendValueInput("VALUE").setCheck(typeExt("StringExpr")).appendField("language of");this.appendValueInput("LANG").setCheck(typeExt("StringExpr")).appendField("is");this.setInputsInline(!0);this.setTooltip("")}};
Blockly.Blocks.sparql_text_charAt={init:function(){this.WHERE_OPTIONS=[[Blockly.Msg.TEXT_CHARAT_FROM_START,"FROM_START"],[Blockly.Msg.TEXT_CHARAT_FROM_END,"FROM_END"],[Blockly.Msg.TEXT_CHARAT_FIRST,"FIRST"],[Blockly.Msg.TEXT_CHARAT_LAST,"LAST"],[Blockly.Msg.TEXT_CHARAT_RANDOM,"RANDOM"]];this.setHelpUrl(Blockly.Msg.TEXT_CHARAT_HELPURL);this.setColour(SparqlBlocks.Blocks.text.HUE);this.setOutput(!0,"StringExpr");this.appendValueInput("VALUE").setCheck(typeExt("StringExpr")).appendField(Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT);
this.appendDummyInput("AT");this.setInputsInline(!0);this.updateAt_(!0);this.setTooltip(Blockly.Msg.TEXT_CHARAT_TOOLTIP)},mutationToDom:function(){var a=document.createElement("mutation"),b=this.getInput("AT").type==Blockly.INPUT_VALUE;a.setAttribute("at",b);return a},domToMutation:function(a){a="false"!=a.getAttribute("at");this.updateAt_(a)},updateAt_:function(a){this.removeInput("AT");this.removeInput("ORDINAL",!0);a?(this.appendValueInput("AT").setCheck(typeExt("NumberExpr")),Blockly.Msg.ORDINAL_NUMBER_SUFFIX&&
this.appendDummyInput("ORDINAL").appendField(Blockly.Msg.ORDINAL_NUMBER_SUFFIX)):this.appendDummyInput("AT");Blockly.Msg.TEXT_CHARAT_TAIL&&(this.removeInput("TAIL",!0),this.appendDummyInput("TAIL").appendField(Blockly.Msg.TEXT_CHARAT_TAIL));var b=new Blockly.FieldDropdown(this.WHERE_OPTIONS,function(b){var e="FROM_START"==b||"FROM_END"==b;if(e!=a){var d=this.sourceBlock_;d.updateAt_(e);d.setFieldValue(b,"WHERE");return null}});this.getInput("AT").appendField(b,"WHERE")}};
Blockly.Blocks.sparql_text_getSubstring={init:function(){this.WHERE_OPTIONS_1=[[Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START,"FROM_START"],[Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END,"FROM_END"],[Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST,"FIRST"]];this.WHERE_OPTIONS_2=[[Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START,"FROM_START"],[Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END,"FROM_END"],[Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST,"LAST"]];this.setHelpUrl(Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL);
this.setColour(SparqlBlocks.Blocks.text.HUE);this.appendValueInput("STRING").setCheck("String").appendField(Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT);this.appendDummyInput("AT1");this.appendDummyInput("AT2");Blockly.Msg.TEXT_GET_SUBSTRING_TAIL&&this.appendDummyInput("TAIL").appendField(Blockly.Msg.TEXT_GET_SUBSTRING_TAIL);this.setInputsInline(!0);this.setOutput(!0,"StringExpr");this.updateAt_(1,!0);this.updateAt_(2,!0);this.setTooltip(Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP)},mutationToDom:function(){var a=
document.createElement("mutation"),b=this.getInput("AT1").type==Blockly.INPUT_VALUE;a.setAttribute("at1",b);b=this.getInput("AT2").type==Blockly.INPUT_VALUE;a.setAttribute("at2",b);return a},domToMutation:function(a){var b="true"==a.getAttribute("at1");a="true"==a.getAttribute("at2");this.updateAt_(1,b);this.updateAt_(2,a)},updateAt_:function(a,b){this.removeInput("AT"+a);this.removeInput("ORDINAL"+a,!0);b?(this.appendValueInput("AT"+a).setCheck(typeExt("NumberExpr")),Blockly.Msg.ORDINAL_NUMBER_SUFFIX&&
this.appendDummyInput("ORDINAL"+a).appendField(Blockly.Msg.ORDINAL_NUMBER_SUFFIX)):this.appendDummyInput("AT"+a);2==a&&Blockly.Msg.TEXT_GET_SUBSTRING_TAIL&&(this.removeInput("TAIL",!0),this.appendDummyInput("TAIL").appendField(Blockly.Msg.TEXT_GET_SUBSTRING_TAIL));var c=new Blockly.FieldDropdown(this["WHERE_OPTIONS_"+a],function(c){var d="FROM_START"==c||"FROM_END"==c;if(d!=b){var f=this.sourceBlock_;f.updateAt_(a,d);f.setFieldValue(c,"WHERE"+a);return null}});this.getInput("AT"+a).appendField(c,
"WHERE"+a);1==a&&this.moveInputBefore("AT1","AT2")}};
Blockly.Blocks.sparql_text_changeCase={init:function(){var a=[[Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE,"UPPERCASE"],[Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE,"LOWERCASE"],[Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE,"TITLECASE"]];this.setHelpUrl(Blockly.Msg.TEXT_CHANGECASE_HELPURL);this.setColour(SparqlBlocks.Blocks.text.HUE);this.appendValueInput("TEXT").setCheck(typeExt("StringExpr")).appendField(new Blockly.FieldDropdown(a),"CASE");this.setOutput(!0,"StringExpr");this.setTooltip(Blockly.Msg.TEXT_CHANGECASE_TOOLTIP)}};
Blockly.Blocks.sparql_text_trim={init:function(){var a=[[Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH,"BOTH"],[Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT,"LEFT"],[Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT,"RIGHT"]];this.setHelpUrl(Blockly.Msg.TEXT_TRIM_HELPURL);this.setColour(SparqlBlocks.Blocks.text.HUE);this.appendValueInput("TEXT").setCheck(typeExt("StringExpr")).appendField(new Blockly.FieldDropdown(a),"MODE");this.setOutput(!0,"StringExpr");this.setTooltip(Blockly.Msg.TEXT_TRIM_TOOLTIP)}};/*

 Visual Blocks Editor

 Copyright 2012 Google Inc.
 https://developers.google.com/blockly/

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
SparqlBlocks.Blocks.tuple={};typeExt=SparqlBlocks.Types.getExtension;
Blockly.Blocks.sparql_tuple={init:function(){this.setHelpUrl(Blockly.Msg.CONTROLS_IF_HELPURL);this.setColour(330);this.appendValueInput("VAL0").setCheck(typeExt("Resource"));this.setPreviousStatement(!0,"Tuple");this.setNextStatement(!0,"Tuple");this.setMutator(new Blockly.Mutator(["controls_if_elseif","controls_if_else"]));this.setTooltip("");this.valCount_=0},mutationToDom:function(){if(!this.valCount_)return null;var a=document.createElement("mutation");this.valCount_&&a.setAttribute("valCount",
this.valCount_);return a},domToMutation:function(a){this.valCount_=parseInt(a.getAttribute("valCount"),10);for(a=1;a<=this.valCount_;a++)this.appendValueInput("VAL"+a).setCheck(typeExt("Resource"))},decompose:function(a){var b=Blockly.Block.obtain(a,"sparql_tuple_tuple");b.initSvg();for(var c=b.getInput("STACK").connection,e=1;e<=this.valCount_;e++){var d=Blockly.Block.obtain(a,"sparql_tuple_value");d.initSvg();c.connect(d.previousConnection);c=d.nextConnection}return b},compose:function(a){for(var b=
this.valCount_;0<b;b--)this.removeInput("VAL"+b);this.valCount_=0;for(a=a.getInputTargetBlock("STACK");a;){switch(a.type){case "col":this.valCount_++;b=this.appendValueInput("VAL"+this.valCount_).setCheck(typeExt("Resource"));a.valueConnection_&&b.connection.connect(a.valueConnection_);break;default:throw"Unknown block type.";}a=a.nextConnection&&a.nextConnection.targetBlock()}},saveConnections:function(a){a=a.getInputTargetBlock("STACK");for(var b=1;a;){switch(a.type){case "sparql_tuple_value":var c=
this.getInput("VAL"+b);a.valueConnection_=c&&c.connection.targetConnection;b++;break;default:throw"Unknown block type.";}a=a.nextConnection&&a.nextConnection.targetBlock()}}};Blockly.Blocks.sparql_tuple_tuple={init:function(){this.setColour(330);this.appendDummyInput().appendField("tuple");this.appendStatementInput("STACK");this.setTooltip("");this.contextMenu=!1}};
Blockly.Blocks.sparql_tuple_value={init:function(){this.setColour(330);this.appendDummyInput().appendField("value");this.setPreviousStatement(!0);this.setNextStatement(!0);this.setTooltip("");this.contextMenu=!1}};/*

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
SparqlBlocks.Blocks.variables={};SparqlBlocks.Blocks.variables.HUE=330;Blockly.Blocks.sparql_variable={init:function(){this.setHelpUrl("http://www.example.com/");this.setColour(SparqlBlocks.Blocks.variables.HUE);this.appendDummyInput().appendField(new Blockly.FieldVariable,"VAR");this.setOutput(!0,"Var");this.setTooltip("")},getVars:function(){return[this.getFieldValue("VAR")]},renameVar:function(a,b){Blockly.Names.equals(a,this.getFieldValue("VAR"))&&this.setFieldValue(b,"VAR")}};
Blockly.Blocks.variables_get=Blockly.Blocks.sparql_variable;Blockly.Blocks.variables_set=null;