// Do not edit this file; automatically generated by build.py.
'use strict';

/*

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
SparqlBlocks.Sparql=new Blockly.Generator("Sparql");SparqlBlocks.Sparql.addReservedWords("");SparqlBlocks.Sparql.STMNT_BRK="###\n";SparqlBlocks.Sparql.STMNT_BRK_RE=/###\n/;SparqlBlocks.Sparql.stmJoin=function(a,b){var c=a.split(SparqlBlocks.Sparql.STMNT_BRK_RE);c.pop();return c.join(b)};SparqlBlocks.Sparql.ORDER_ATOMIC=0;SparqlBlocks.Sparql.ORDER_MEMBER=1;SparqlBlocks.Sparql.ORDER_NEW=1;SparqlBlocks.Sparql.ORDER_FUNCTION_CALL=2;SparqlBlocks.Sparql.ORDER_INCREMENT=3;
SparqlBlocks.Sparql.ORDER_DECREMENT=3;SparqlBlocks.Sparql.ORDER_LOGICAL_NOT=4;SparqlBlocks.Sparql.ORDER_BITWISE_NOT=4;SparqlBlocks.Sparql.ORDER_UNARY_PLUS=4;SparqlBlocks.Sparql.ORDER_UNARY_NEGATION=4;SparqlBlocks.Sparql.ORDER_TYPEOF=4;SparqlBlocks.Sparql.ORDER_VOID=4;SparqlBlocks.Sparql.ORDER_DELETE=4;SparqlBlocks.Sparql.ORDER_MULTIPLICATION=5;SparqlBlocks.Sparql.ORDER_DIVISION=5;SparqlBlocks.Sparql.ORDER_MODULUS=5;SparqlBlocks.Sparql.ORDER_ADDITION=6;SparqlBlocks.Sparql.ORDER_SUBTRACTION=6;
SparqlBlocks.Sparql.ORDER_BITWISE_SHIFT=7;SparqlBlocks.Sparql.ORDER_RELATIONAL=8;SparqlBlocks.Sparql.ORDER_IN=8;SparqlBlocks.Sparql.ORDER_INSTANCEOF=8;SparqlBlocks.Sparql.ORDER_EQUALITY=9;SparqlBlocks.Sparql.ORDER_BITWISE_AND=10;SparqlBlocks.Sparql.ORDER_BITWISE_XOR=11;SparqlBlocks.Sparql.ORDER_BITWISE_OR=12;SparqlBlocks.Sparql.ORDER_LOGICAL_AND=13;SparqlBlocks.Sparql.ORDER_LOGICAL_OR=14;SparqlBlocks.Sparql.ORDER_CONDITIONAL=15;SparqlBlocks.Sparql.ORDER_ASSIGNMENT=16;
SparqlBlocks.Sparql.ORDER_COMMA=17;SparqlBlocks.Sparql.ORDER_NONE=99;SparqlBlocks.Sparql.init=function(a){};SparqlBlocks.Sparql.finish=function(a){return a};SparqlBlocks.Sparql.scrubNakedValue=function(a){return a+";\n"};SparqlBlocks.Sparql.quote_=function(a){a=a.replace(/\\/g,"\\\\").replace(/\n/g,"\\\n").replace(/'/g,"\\'");return"'"+a+"'"};
SparqlBlocks.Sparql.scrub_=function(a,b){var c="";if(!a.outputConnection||!a.outputConnection.targetConnection){var d=a.getCommentText();d&&(c+=SparqlBlocks.Sparql.prefixLines(d,"// ")+"\n");for(var e=0;e<a.inputList.length;e++)a.inputList[e].type==Blockly.INPUT_VALUE&&(d=a.inputList[e].connection.targetBlock())&&(d=SparqlBlocks.Sparql.allNestedComments(d))&&(c+=SparqlBlocks.Sparql.prefixLines(d,"// "))}e=a.nextConnection&&a.nextConnection.targetBlock();e=SparqlBlocks.Sparql.blockToCode(e);return c+
b+e};/*

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
SparqlBlocks.Sparql.bgp={};SparqlBlocks.Sparql.bgp.extendVerb_=function(a){return"rdfs:subClassOf"==a?"rdfs:subClassOf*":a};SparqlBlocks.Sparql.sparql_isa=function(a){return(a=SparqlBlocks.Sparql.valueToCode(a,"TYPE",SparqlBlocks.Sparql.ORDER_ATOMIC))?"a "+a+SparqlBlocks.Sparql.STMNT_BRK:""};
SparqlBlocks.Sparql.sparql_verb_object=function(a){var b=SparqlBlocks.Sparql.valueToCode(a,"VERB",SparqlBlocks.Sparql.ORDER_ATOMIC);a=SparqlBlocks.Sparql.valueToCode(a,"OBJECT",SparqlBlocks.Sparql.ORDER_ATOMIC);return b?SparqlBlocks.Sparql.bgp.extendVerb_(b)+" "+(a?a:"[]")+SparqlBlocks.Sparql.STMNT_BRK:""};
SparqlBlocks.Sparql.sparql_reverseVerb_object=function(a){var b=SparqlBlocks.Sparql.valueToCode(a,"VERB",SparqlBlocks.Sparql.ORDER_ATOMIC);a=SparqlBlocks.Sparql.valueToCode(a,"OBJECT",SparqlBlocks.Sparql.ORDER_ATOMIC);return b?"^"+SparqlBlocks.Sparql.bgp.extendVerb_(b)+" "+(a?a:"[]")+SparqlBlocks.Sparql.STMNT_BRK:""};
SparqlBlocks.Sparql.sparql_typedsubject_propertylist=function(a){var b=SparqlBlocks.Sparql.valueToCode(a,"SUBJECT",SparqlBlocks.Sparql.ORDER_ATOMIC),c=SparqlBlocks.Sparql.valueToCode(a,"TYPE",SparqlBlocks.Sparql.ORDER_ATOMIC);a=SparqlBlocks.Sparql.stmJoin(SparqlBlocks.Sparql.statementToCode(a,"PROPERTY_LIST"),";\n");return c||""!=a?(b?b:"[]")+(c?" a "+c+(""!=a?";":""):"")+(""!=a?"\n"+a:"")+SparqlBlocks.Sparql.STMNT_BRK:""};
SparqlBlocks.Sparql.sparql_subject_propertylist=function(a){var b=SparqlBlocks.Sparql.valueToCode(a,"SUBJECT",SparqlBlocks.Sparql.ORDER_ATOMIC);a=SparqlBlocks.Sparql.stmJoin(SparqlBlocks.Sparql.statementToCode(a,"PROPERTY_LIST"),";\n");return""!=a?(b?b:"[]")+(""!=a?"\n"+a:"")+SparqlBlocks.Sparql.STMNT_BRK:""};var generateAnonSubject=function(a,b){return[a||""!=b?"[\n"+(a?" a "+a+(""!=b?";\n":""):"")+(""!=b?b:"")+"\n]":"[]",SparqlBlocks.Sparql.ORDER_ATOMIC]};
SparqlBlocks.Sparql.sparql_anontypedsubject_propertylist=function(a){var b=SparqlBlocks.Sparql.valueToCode(a,"TYPE",SparqlBlocks.Sparql.ORDER_ATOMIC);a=SparqlBlocks.Sparql.stmJoin(SparqlBlocks.Sparql.statementToCode(a,"PROPERTY_LIST"),";\n");return generateAnonSubject(b,a)};SparqlBlocks.Sparql.sparql_anonsubject_propertylist=function(a){a=SparqlBlocks.Sparql.stmJoin(SparqlBlocks.Sparql.statementToCode(a,"PROPERTY_LIST"),";\n");return generateAnonSubject(null,a)};/*

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
SparqlBlocks.Sparql.control={};SparqlBlocks.Sparql.sparql_filter=function(a){return(a=SparqlBlocks.Sparql.valueToCode(a,"CONDITION",SparqlBlocks.Sparql.ORDER_NONE))?"FILTER("+a+")"+SparqlBlocks.Sparql.STMNT_BRK:""};
SparqlBlocks.Sparql.sparql_union=function(a){var b=SparqlBlocks.Sparql.stmJoin(SparqlBlocks.Sparql.statementToCode(a,"OP1"),".\n");a=SparqlBlocks.Sparql.stmJoin(SparqlBlocks.Sparql.statementToCode(a,"OP2"),".\n");return""==b?""==a?"":"{\n"+a+"\n}"+SparqlBlocks.Sparql.STMNT_BRK:""==a?"{\n"+b+"\n}"+SparqlBlocks.Sparql.STMNT_BRK:"{\n"+b+"\n} UNION {\n"+a+"\n}"+SparqlBlocks.Sparql.STMNT_BRK};
SparqlBlocks.Sparql.sparql_optional=function(a){a=SparqlBlocks.Sparql.stmJoin(SparqlBlocks.Sparql.statementToCode(a,"OP"),".\n");return""==a?"":"OPTIONAL {\n"+a+"\n}"+SparqlBlocks.Sparql.STMNT_BRK};/*

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
SparqlBlocks.Sparql.logic={};SparqlBlocks.Sparql.sparql_logic_compare=function(a){var b={EQ:"=",NEQ:"!=",LT:"<",LTE:"<=",GT:">",GTE:">="}[a.getFieldValue("OP")],c="="==b||"!="==b?SparqlBlocks.Sparql.ORDER_EQUALITY:SparqlBlocks.Sparql.ORDER_RELATIONAL,d=SparqlBlocks.Sparql.valueToCode(a,"A",c)||"0";a=SparqlBlocks.Sparql.valueToCode(a,"B",c)||"0";return[d+" "+b+" "+a,c]};
SparqlBlocks.Sparql.sparql_logic_operation=function(a){var b="AND"==a.getFieldValue("OP")?"&&":"||",c="&&"==b?SparqlBlocks.Sparql.ORDER_LOGICAL_AND:SparqlBlocks.Sparql.ORDER_LOGICAL_OR,d=SparqlBlocks.Sparql.valueToCode(a,"A",c);a=SparqlBlocks.Sparql.valueToCode(a,"B",c);if(d||a){var e="&&"==b?"true":"false";d||(d=e);a||(a=e)}else a=d="false";return[d+" "+b+" "+a,c]};
SparqlBlocks.Sparql.sparql_logic_negate=function(a){var b=SparqlBlocks.Sparql.ORDER_LOGICAL_NOT;return["!"+(SparqlBlocks.Sparql.valueToCode(a,"BOOL",b)||"true"),b]};SparqlBlocks.Sparql.sparql_logic_boolean=function(a){return["TRUE"==a.getFieldValue("BOOL")?"true":"false",SparqlBlocks.Sparql.ORDER_ATOMIC]};
SparqlBlocks.Sparql.sparql_logic_ternary=function(a){var b=SparqlBlocks.Sparql.valueToCode(a,"IF",SparqlBlocks.Sparql.ORDER_COMMA)||"false",c=SparqlBlocks.Sparql.valueToCode(a,"THEN",SparqlBlocks.Sparql.ORDER_COMMA)||'""';a=SparqlBlocks.Sparql.valueToCode(a,"ELSE",SparqlBlocks.Sparql.ORDER_COMMA)||'""';return["IF("+b+", "+c+", "+a+")",SparqlBlocks.Sparql.ORDER_FUNCTION_CALL]};/*

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
SparqlBlocks.Sparql.main={};
SparqlBlocks.Sparql.sparql_select=function(a){for(var b=SparqlBlocks.Sparql.stmJoin(SparqlBlocks.Sparql.statementToCode(a,"WHERE"),".\n"),c=a.getFieldValue("LIMIT"),b="SELECT DISTINCT * WHERE {\n"+b+"\n}",d=null,e=1;;e++){var g=SparqlBlocks.Sparql.valueToCode(this,"ORDER_FIELD"+e,SparqlBlocks.Sparql.ORDER_NONE);if(g){var h=a.getFieldValue("ORDER_DIRECTION"+e),d=d?d+", ":"ORDER BY ";h&&"DESC"==h&&(d+="DESC");d+="("+g+")"}else break}d&&(b+="\n"+d);c&&(b+="\nLIMIT "+c);a=b.match(/[^(|!/\^,;\x20|\x09|\x0D|\x0A]+[\x20|\x09|\x0D|\x0A]*:/g);
c=null;a&&(c=a.map(function(a){return a.substr(0,a.length-1).trim()}));var f="";c&&c.forEach(function(a){var b=SparqlBlocks.Prefixes.lookForPrefix(a);b&&(f+="PREFIX "+a+":\t<"+b+">\n")});0<f.length&&(b=f+"\n"+b);return[b,SparqlBlocks.Sparql.ORDER_ATOMIC]};SparqlBlocks.Sparql.sparql_prefixed_iri=function(a){var b=a.getFieldValue("PREFIX");a=a.getFieldValue("LOCAL_NAME");return[b+":"+a,SparqlBlocks.Sparql.ORDER_ATOMIC]};
SparqlBlocks.Sparql.sparql_iri=function(a){return["<"+a.getFieldValue("IRI")+">",SparqlBlocks.Sparql.ORDER_ATOMIC]};SparqlBlocks.Sparql.variables_get=function(a){return["?"+a.getFieldValue("VAR"),SparqlBlocks.Sparql.ORDER_ATOMIC]};/*

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
SparqlBlocks.Sparql.math={};SparqlBlocks.Sparql.sparql_math_number=function(a){a=a.getFieldValue("NUM");var b=""+parseInt(a);if(a==b)return[a,SparqlBlocks.Sparql.ORDER_ATOMIC];b=parseFloat(a);if(!isNaN(b))return[""+b,SparqlBlocks.Sparql.ORDER_ATOMIC];throw"Not a number: "+a;};
SparqlBlocks.Sparql.sparql_math_arithmetic=function(a){var b={ADD:[" + ",SparqlBlocks.Sparql.ORDER_ADDITION],MINUS:[" - ",SparqlBlocks.Sparql.ORDER_SUBTRACTION],MULTIPLY:[" * ",SparqlBlocks.Sparql.ORDER_MULTIPLICATION],DIVIDE:[" / ",SparqlBlocks.Sparql.ORDER_DIVISION]}[a.getFieldValue("OP")],c=b[0],b=b[1],d=SparqlBlocks.Sparql.valueToCode(a,"A",b)||"0";a=SparqlBlocks.Sparql.valueToCode(a,"B",b)||"0";return[d+c+a,b]};
SparqlBlocks.Sparql.sparql_math_single=function(a){var b=a.getFieldValue("OP"),c;if("NEG"==b)return a=SparqlBlocks.Sparql.valueToCode(a,"NUM",SparqlBlocks.Sparql.ORDER_UNARY_NEGATION)||"0","-"==a[0]&&(a=" "+a),["-"+a,SparqlBlocks.Sparql.ORDER_UNARY_NEGATION];a=SparqlBlocks.Sparql.valueToCode(a,"NUM",SparqlBlocks.Sparql.ORDER_NONE)||"0";switch(b){case "ABS":c="ABS("+a+")";break;case "ROUND":c="ROUND("+a+")";break;case "ROUNDUP":c="CEIL("+a+")";break;case "ROUNDDOWN":c="FLOOR("+a+")"}if(c)return[c,
SparqlBlocks.Sparql.ORDER_FUNCTION_CALL];throw"Unknown math operator: "+b;};SparqlBlocks.Sparql.isWhole=function(a){return["FLOOR("+a+") = "+a,SparqlBlocks.Sparql.ORDER_EQUALITY]};SparqlBlocks.Sparql.isNotWhole=function(a){return["FLOOR("+a+") != "+a,SparqlBlocks.Sparql.ORDER_EQUALITY]};SparqlBlocks.Sparql.divisible=function(a,b){return SparqlBlocks.Sparql.isWhole(a+" / "+b)[0]};SparqlBlocks.Sparql.notDivisible=function(a,b){return SparqlBlocks.Sparql.isNotWhole(a+" / "+b)[0]};
SparqlBlocks.Sparql.sparql_math_number_property=function(a){var b=SparqlBlocks.Sparql.valueToCode(a,"NUMBER_TO_CHECK",SparqlBlocks.Sparql.ORDER_DIVISION)||"0";switch(a.getFieldValue("PROPERTY")){case "EVEN":return SparqlBlocks.Sparql.divisible(b,"2");case "ODD":return SparqlBlocks.Sparql.notDivisible(b,"2");case "WHOLE":return SparqlBlocks.Sparql.isWhole(b);case "POSITIVE":return[b+" > 0",SparqlBlocks.Sparql.ORDER_RELATIONAL];case "NEGATIVE":return[b+" < 0",SparqlBlocks.Sparql.ORDER_RELATIONAL];case "DIVISIBLE_BY":return a=
SparqlBlocks.Sparql.valueToCode(a,"DIVISOR",SparqlBlocks.Sparql.ORDER_MODULUS)||"0",SparqlBlocks.Sparql.divisible(b,a)}};SparqlBlocks.Sparql.sparql_math_round=SparqlBlocks.Sparql.sparql_math_single;SparqlBlocks.Sparql.idivAbs=function(a,b){return["FLOOR(ABS("+a+" / "+b+"))",SparqlBlocks.Sparql.ORDER_FUNCTION_CALL]};SparqlBlocks.Sparql.idiv=function(a,b){return[SparqlBlocks.Sparql.idivAbs(a,b)[0]+" * (ABS("+a+") / "+a+") * (ABS("+b+") / "+b+")",SparqlBlocks.Sparql.ORDER_MULTIPLICATION]};
SparqlBlocks.Sparql.modulo=function(a,b){return[a+" - "+SparqlBlocks.Sparql.idivAbs(a,b)[0]+" * ABS("+a+") / "+a+" * ABS("+b+")",SparqlBlocks.Sparql.ORDER_SUBTRACTION]};SparqlBlocks.Sparql.sparql_math_modulo=function(a){var b=SparqlBlocks.Sparql.valueToCode(a,"DIVIDEND",SparqlBlocks.Sparql.ORDER_DIVISION)||"0";a=SparqlBlocks.Sparql.valueToCode(a,"DIVISOR",SparqlBlocks.Sparql.ORDER_DIVISION)||"0";return SparqlBlocks.Sparql.modulo(b,a)};
SparqlBlocks.Sparql.sparql_math_constrain=function(a){var b=SparqlBlocks.Sparql.valueToCode(a,"VALUE",SparqlBlocks.Sparql.ORDER_RELATIONAL)||"0",c=SparqlBlocks.Sparql.valueToCode(a,"LOW",SparqlBlocks.Sparql.ORDER_RELATIONAL);a=SparqlBlocks.Sparql.valueToCode(a,"HIGH",SparqlBlocks.Sparql.ORDER_RELATIONAL);return["IF("+b+" < "+c+", "+c+", IF("+b+" > "+a+", "+a+", "+b+") )",SparqlBlocks.Sparql.ORDER_FUNCTION_CALL]};
SparqlBlocks.Sparql.sparql_math_random_int=function(a){var b=SparqlBlocks.Sparql.valueToCode(a,"FROM",SparqlBlocks.Sparql.ORDER_ADDITION)||"0";return["FLOOR(RAND() * ("+(SparqlBlocks.Sparql.valueToCode(a,"TO",SparqlBlocks.Sparql.ORDER_SUBTRACTION)||"0")+" - "+b+" + 1) + "+b+")",SparqlBlocks.Sparql.ORDER_FUNCTION_CALL]};SparqlBlocks.Sparql.sparql_math_random_float=function(a){return["RAND()",SparqlBlocks.Sparql.ORDER_FUNCTION_CALL]};/*

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

   http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
SparqlBlocks.Sparql.text={};SparqlBlocks.Sparql.sparql_text=function(a){return[SparqlBlocks.Sparql.quote_(a.getFieldValue("TEXT")),SparqlBlocks.Sparql.ORDER_ATOMIC]};SparqlBlocks.Sparql.sparql_text_with_lang=function(a){var b=SparqlBlocks.Sparql.quote_(a.getFieldValue("TEXT"));(a=a.getFieldValue("LANG"))&&0<a.length&&(b+="@"+a);return[b,SparqlBlocks.Sparql.ORDER_ATOMIC]};
SparqlBlocks.Sparql.sparql_text_join=function(a){var b;if(0==a.itemCount_)return["''",SparqlBlocks.Sparql.ORDER_ATOMIC];if(1==a.itemCount_)b=SparqlBlocks.Sparql.valueToCode(a,"ADD0",SparqlBlocks.Sparql.ORDER_NONE)||"''",b="STR("+b+")";else if(2==a.itemCount_)b=SparqlBlocks.Sparql.valueToCode(a,"ADD0",SparqlBlocks.Sparql.ORDER_NONE)||"''",a=SparqlBlocks.Sparql.valueToCode(a,"ADD1",SparqlBlocks.Sparql.ORDER_NONE)||"''",b="CONCAT(STR("+b+"), STR("+a+"))";else{b=Array(a.itemCount_);for(var c=0;c<a.itemCount_;c++)b[c]=
SparqlBlocks.Sparql.valueToCode(a,"ADD"+c,SparqlBlocks.Sparql.ORDER_NONE)||"''";b="CONCAT(STR("+b.join("), STR(")+"))"}return[b,SparqlBlocks.Sparql.ORDER_FUNCTION_CALL]};SparqlBlocks.Sparql.sparql_text_length=function(a){return["STRLEN("+(SparqlBlocks.Sparql.valueToCode(a,"VALUE",SparqlBlocks.Sparql.ORDER_NONE)||"''")+")",SparqlBlocks.Sparql.ORDER_FUNCTION_CALL]};
SparqlBlocks.Sparql.sparql_text_isEmpty=function(a){return["STRLEN("+(SparqlBlocks.Sparql.valueToCode(a,"VALUE",SparqlBlocks.Sparql.ORDER_NONE)||"''")+") == 0",SparqlBlocks.Sparql.ORDER_EQUALITY]};SparqlBlocks.Sparql.sparql_text_contains=function(a){var b=SparqlBlocks.Sparql.valueToCode(a,"FIND",SparqlBlocks.Sparql.ORDER_COMMA)||"''";return["CONTAINS("+(SparqlBlocks.Sparql.valueToCode(a,"VALUE",SparqlBlocks.Sparql.ORDER_COMMA)||"''")+", "+b+")",SparqlBlocks.Sparql.ORDER_FUNCTION_CALL]};
SparqlBlocks.Sparql.sparql_text_lang=function(a){var b=SparqlBlocks.Sparql.valueToCode(a,"LANG",SparqlBlocks.Sparql.ORDER_COMMA)||"''";return["LANGMATCHES(LANG("+(SparqlBlocks.Sparql.valueToCode(a,"VALUE",SparqlBlocks.Sparql.ORDER_NONE)||"''")+"), "+b+")",SparqlBlocks.Sparql.ORDER_FUNCTION_CALL]};
SparqlBlocks.Sparql.sparql_text_charAt=function(a){var b=a.getFieldValue("WHERE")||"FROM_START",c=SparqlBlocks.Sparql.valueToCode(a,"AT",SparqlBlocks.Sparql.ORDER_SUBTRACTION)||"1";a=SparqlBlocks.Sparql.valueToCode(a,"VALUE",SparqlBlocks.Sparql.ORDER_COMMA)||"''";switch(b){case "FIRST":return["SUBSTR("+a+", 1, 1)",SparqlBlocks.Sparql.ORDER_FUNCTION_CALL];case "LAST":return["SUBSTR("+a+", STRLEN("+a+"), 1)",SparqlBlocks.Sparql.ORDER_FUNCTION_CALL];case "FROM_START":return["SUBSTR("+a+", "+c+", 1)",
SparqlBlocks.Sparql.ORDER_FUNCTION_CALL];case "FROM_END":return["SUBSTR("+a+", STRLEN("+a+") + 1 - "+c+", 1)",SparqlBlocks.Sparql.ORDER_FUNCTION_CALL]}throw"Unhandled option (text_charAt).";};
SparqlBlocks.Sparql.sparql_text_getSubstring=function(a){var b=SparqlBlocks.Sparql.valueToCode(a,"STRING",SparqlBlocks.Sparql.ORDER_COMMA)||"''",c=a.getFieldValue("WHERE1"),d=a.getFieldValue("WHERE2"),e=SparqlBlocks.Sparql.valueToCode(a,"AT1",SparqlBlocks.Sparql.ORDER_SUBTRACTION)||"1";a=SparqlBlocks.Sparql.valueToCode(a,"AT2",SparqlBlocks.Sparql.ORDER_ADDITION)||"1";if("FIRST"!=c||"LAST"!=d){if("FIRST"==c)c="1";else if("LAST"==c)c="STRLEN("+b+")";else if("FROM_START"==c)c=e;else if("FROM_END"==c)c=
"STRLEN("+b+") + 1 - "+e;else throw"Unhandled option (text_getSubstring): "+c;if("FIRST"==d)d="2 - "+c;else if("LAST"==d)d=null;else if("FROM_START"==d)d=a+" + 1 - "+c;else if("FROM_END"==d)d="STRLEN("+b+") + 2 - "+a+" - "+c;else throw"Unhandled option (text_getSubstring): "+d;return[d?"SUBSTR("+b+", "+c+", "+d+")":"SUBSTR("+b+", "+c+")",SparqlBlocks.Sparql.ORDER_FUNCTION_CALL]}};
SparqlBlocks.Sparql.sparql_text_changeCase=function(a){var b=a.getFieldValue("CASE"),c={UPPERCASE:"UCASE",LOWERCASE:"LCASE"}[b];if(c)return a=SparqlBlocks.Sparql.valueToCode(a,"TEXT",SparqlBlocks.Sparql.ORDER_NONE)||"''",[c+"("+a+")",SparqlBlocks.Sparql.ORDER_FUNCTION_CALL];throw"Unknown case type: "+b;};